version: "3"
services:
  backend:
    image: backend-flask
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: "backend-app"
    volumes:
        - ./backend:/app
    ports:
      - "8081:8081"
  frontend:
    image: frontend-angular
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: "frontend-app"
    volumes:
        - ./frontend/src:/app/src
    ports:
      - "4200:4200"
